version: '3.8'

services:
  web:
    build: .
    container_name: bookstore-web
    ports:
      - "8081:80"
    volumes:
      - /var/www/html/vendor
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bookstore-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./scripts/seedData3.sql:/docker-entrypoint-initdb.d/seedData3.sql

volumes:
  db-data: