version: '3.8'

services:
  web:
    build: .
    container_name: bookstore-web
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - DBHOST=db
      - DB_PORT=3306
      - DB_DATABASE=bookstore
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bookstore-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
    volumes:
      - db-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d/seedData2.sql

volumes:
  db-data: